import Link from 'next/link'

import 'bootstrap/dist/css/bootstrap.min.css';

// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header>
          <ul>
            <li><Link href={"/groups/search"}>groups</Link></li>
            <li><Link href={"/users/search"}>users</Link></li>
          </ul>


        </header>
        {children}</body>
    </html>
  )
}
